### ISSUE TITLE
Support for new MSBuild .csproj format

### ISSUE THREAD

**Issue by rjmurillo** [RSuter/NuGetReferenceSwitcher#29]
Could not load project NewProjectFormat
(new MSBuild .csproj are not supported, unload them first): 
```
System.NullReferenceException: Object reference not set to an instance of an object.

   at NuGetReferenceSwitcher.Presentation.Models.ProjectModel.LoadReferences()
   at NuGetReferenceSwitcher.Presentation.ViewModels.MainDialogModel.GetAllProjects(IEnumerable`1 objects)
```

**Comment by arpit-nagar** [comment]
Any update on this ??
We are also facing same issue.

**Comment by watashiSHUN** [comment]
+1

**Comment by RSuter** [comment]
I havent planned to implement this feature - however i accpect prs... im working on a command line version for .net core with this feature, because it is much simpler than developing a vs extension...

**Comment by monty241** [comment]
Great extension, would even be better with this issue, so +1.

**Comment by michael-freidgeim-webjet** [comment]
@RSuter,  

> command line version for .net core with this feature

Will it be in the same repository? Or in the  separate repository? When are you planning to release it?

**Comment by monty241** [comment]
As an alternative, you might want to use condition=... in your itemgroups. In that way, depending on $(Configuration) you can use referenced packages or project references easily with one csproj file. Works in both old and new csproj format.

**Comment by RSuter** [comment]
@monty241 this is a really good idea. After I changed all my projects to this, I really no longer need this extension :-)

@michael-freidgeim-webjet i'm not yet sure if I open-source this tool, I'm already spending a lot of time for open source (see my other projects), and I also need to earn some money sometimes or have some free time... the current is not really working very well.

**Comment by gohar94** [comment]
Any updates on this?

**Comment by RicoSuter** [comment]
This is not planned, use DNT instead: https://github.com/RicoSuter/DNT
