### ISSUE TITLE
Error HRESULT E_FAIL has been returned from a call to a COM component.

### ISSUE THREAD

**Issue by Christopher1065** [rsuter/NuGetReferenceSwitcher#5]
Upon switching from Project references to Nuget references. 

![image](https://cloud.githubusercontent.com/assets/1360605/8414249/86bd6ee8-1e4b-11e5-8b03-65be8671572c.png)

Error occurred looking for one of our internal custom packages: 
"C:\\src\\vso\\Ganon\\master\\packages\\Iro.Cache.1.0.2744.372\\lib\\net451\\Iro.Cache.dll"

Error code was: -2147467259

So my first guess is it is trying to add back references that don't exist anymore. 

Note that this happened in the experimental hive so in theory no other plug ins should be affecting yours. 

Stack Tace: 
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at VSLangProj.References.Add(String bstrPath)
   at NuGetReferenceSwitcher.Presentation.Models.ProjectModel.AddReference(String assemblyPath) in c:\src\Open\NuGetReferenceSwitcher-master\src\NuGetReferenceSwitcher.Presentation\Models\ProjectModel.cs:line 101
   at NuGetReferenceSwitcher.Presentation.ViewModels.MainDialogModel.<SwitchToNuGetReferencesAsync>b__1a() in c:\src\Open\NuGetReferenceSwitcher-master\src\NuGetReferenceSwitcher.Presentation\ViewModels\MainDialogModel.cs:line 175
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MyToolkit.Mvvm.ViewModelBase.<>c__DisplayClass6.<<RunTaskAsync>b__5>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyToolkit.Mvvm.ViewModelBase.<RunTaskAsync>d__0`1.MoveNext()

**Comment by Christopher1065** [comment]
I understand this one better now. It seems that the stored paths in the *.previous.nugetreferenceswitcher file was old. I imagine this happens when there are errors in switching from Nuget references to Project references to start with and then we are in this state where the references from the last conversion are used. Probably better to focus on bugs related to switching to project references and this one should take care of itself.

**Comment by rsuter** [comment]
Nonetheless, we should catch the exception so that vs does not break...

**Comment by rsuter** [comment]
Just added a project path check...
